print("Welcome to the Band Name Generator")
city=input("What's the name of your city you grew up in?")
print(city)
pet=input("What's the name of your pet?")
print(pet)
print(("Your band name could be:" + city + " " + pet))